Fill Missing Values in a Dataset using Python

 Ref :
 
 https://thecleverprogrammer.com/2021/05/29/fill-missing-values-in-a-dataset-using-python/

In [1]:
import numpy as np
data = np.array([[10, np.nan, 8], 
                 [9, 8, np.nan], 
                 [7, 10, 9]])
print(data)

[[10. nan  8.]
 [ 9.  8. nan]
 [ 7. 10.  9.]]


In [2]:
# Filling Values with mean
from sklearn.impute import SimpleImputer
mean_values = SimpleImputer(strategy='mean')
data1 = mean_values.fit_transform(data)
print(data1)

[[10.   9.   8. ]
 [ 9.   8.   8.5]
 [ 7.  10.   9. ]]


In [3]:
# Filling Values with median
from sklearn.impute import SimpleImputer
median_values = SimpleImputer(strategy='median')
data2 = median_values.fit_transform(data)
print(data2)

[[10.   9.   8. ]
 [ 9.   8.   8.5]
 [ 7.  10.   9. ]]


In [4]:
# Filling values with most frequent values
from sklearn.impute import SimpleImputer
most_frequent = SimpleImputer(strategy='most_frequent')
data3 = most_frequent.fit_transform(data)
print(data3)

[[10.  8.  8.]
 [ 9.  8.  8.]
 [ 7. 10.  9.]]
