In [1]:
# import all the lib
import pandas as pd
import numpy as np
import pickle

In [2]:
# read the dataset using pandas
data = pd.read_csv('/kaggle/input/salary-data-simple-linear-regression/Salary_Data.csv')

In [3]:
# This displays the top 5 rows of the data
data.head()

YearsExperience   Salary
0              1.1  39343.0
1              1.3  46205.0
2              1.5  37731.0
3              2.0  43525.0
4              2.2  39891.0

In [4]:
# Provides some information regarding the columns in the data
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 30 entries, 0 to 29
Data columns (total 2 columns):
YearsExperience    30 non-null float64
Salary             30 non-null float64
dtypes: float64(2)
memory usage: 608.0 bytes


In [5]:
# this describes the basic stat behind the dataset used 
data.describe()

YearsExperience         Salary
count        30.000000      30.000000
mean          5.313333   76003.000000
std           2.837888   27414.429785
min           1.100000   37731.000000
25%           3.200000   56720.750000
50%           4.700000   65237.000000
75%           7.700000  100544.750000
max          10.500000  122391.000000

In [6]:
# Cooking the data
X = data['YearsExperience']
X.head()

0    1.1
1    1.3
2    1.5
3    2.0
4    2.2
Name: YearsExperience, dtype: float64

In [7]:
# Cooking the data
y = data['Salary']
y.head()

0    39343.0
1    46205.0
2    37731.0
3    43525.0
4    39891.0
Name: Salary, dtype: float64

In [8]:
# Import Segregating data from scikit learn
from sklearn.model_selection import train_test_split

In [9]:
# Split the data for train and test 
X_train,X_test,y_train,y_test = train_test_split(X,y,train_size=0.7,random_state=100)

In [10]:
# Create new axis for x column
X_train = X_train[:,np.newaxis]
X_test = X_test[:,np.newaxis]

In [11]:
# Importing Linear Regression model from scikit learn
from sklearn.linear_model import LinearRegression

In [12]:
# Fitting the model
lr = LinearRegression()
lr.fit(X_train,y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [13]:
# Predicting the Salary for the Test values
y_pred = lr.predict(X_test)

In [14]:
y_pred

array([ 61208.34198766, 117649.32424949, 125434.28732008,  65100.82352296,
        53423.37891707,  64127.70313914, 118622.44463331, 112783.72233036,
        54396.49930089])

In [15]:
# Intecept and coeff of the line
print('Intercept of the model:',lr.intercept_)
print('Coefficient of the line:',lr.coef_)

Intercept of the model: 25202.887786154883
Coefficient of the line: [9731.20383825]


![](http://)Then it is said to form a line with
# y = 25202.8 + 9731.2x

In [16]:
# Save the trained model as a pickle string.
saved_model = pickle.dumps(lr)

In [17]:
# Load the pickled model
lr_from_pickle = pickle.loads(saved_model)

In [18]:
# Use the loaded pickled model to make predictions
y_pred = lr_from_pickle.predict(X_test)

In [19]:
y_pred

array([ 61208.34198766, 117649.32424949, 125434.28732008,  65100.82352296,
        53423.37891707,  64127.70313914, 118622.44463331, 112783.72233036,
        54396.49930089])

In [20]:
from sklearn.externals import joblib

/opt/conda/lib/python3.6/site-packages/sklearn/externals/joblib/__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


In [21]:
# Save the model as a pickle in a file
joblib.dump(lr, 'simple_linear_regression.pkl')

['simple_linear_regression.pkl']

In [22]:
# Load the model from the file
lr_from_joblib = joblib.load('simple_linear_regression.pkl')

In [23]:
X_test

array([[ 3.7],
       [ 9.5],
       [10.3],
       [ 4.1],
       [ 2.9],
       [ 4. ],
       [ 9.6],
       [ 9. ],
       [ 3. ]])

In [24]:
# Use the loaded model to make predictions
y_pred = lr_from_joblib.predict(X_test)

In [25]:
y_pred

array([ 61208.34198766, 117649.32424949, 125434.28732008,  65100.82352296,
        53423.37891707,  64127.70313914, 118622.44463331, 112783.72233036,
        54396.49930089])

In [26]:
import json
json.dumps(list(lr_from_joblib.predict([[3.5]])))

'[59262.1012200137]'